services:
  - type: web
    name: mlb-bet-predictor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: RUN_TOKEN
        sync: false
